### ISSUE TITLE
Issue on restarting server after saving configuration property 'generator-settings'

### ISSUE THREAD

**Issue by romwil** [Rxflex/kubek-minecraft-dashboard#1]
Am receiving this: 

Failed to start the minecraft server
java.lang.RuntimeException: Could not load invalidly configured property 'generator-settings'

Attempted paper 1.20.6 creation multiple times with different configurations. seems to happen after editing the server.properties via the interface and starting.

**Comment by euforik** [comment]
yes, I confirm, as soon as I go into the server config and save it, the server cannot be started anymore - it writes the changes to the file incorrectly

**Comment by Rxflex** [comment]
Hi, thanks for contacting me, I will try to fix this in the next update, to solve this problem, use changing the server.properties file via file manager or FTP

**Comment by Rxflex** [comment]
@romwil @euforik The problem has been solved, update the application
